version: "3.8"

services:
  frontend:
    image: tu_imagen_frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flask_react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: tu_imagen_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_react_backend
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    expose:
      - 5000
    networks:
      - app_network
    volumes:
      - ./backend/tasks.db:/app/tasks.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge
